### ISSUE TITLE
Bump a new release and update PyPI

### ISSUE THREAD

**Issue by scorphus** [alonho/nosecomplete#14]
3c37b65, for example, is not included in any revision on PyPI, rendering `nosecomplete` useless on Python 3. Please bump a new `0.1.1` release, tag the respective commit and update PyPI.

Thanks!

**Comment by alonho** [comment]
Done. Thanks for asking me to do this (:

**Comment by scorphus** [comment]
Thank you! :+1: I'm glad you updated PyPI! Please, don't forget to push the `0.1.1` tag :smile:

**Comment by alonho** [comment]
Forgot to push --tags. Thanks again.
